CREATE TABLE BOSNET1.dbo.Customer (
	Customer_ID varchar(10) NOT NULL,
	Account_Group varchar(4) NOT NULL,
	Distribution_Channel varchar(2) NOT NULL,
	Division varchar(2) NOT NULL,
	Name1 varchar(40) NOT NULL DEFAULT ('n/a'),
	Name2 varchar(40) NOT NULL DEFAULT ('n/a'),
	Street varchar(40) NOT NULL DEFAULT ('n/a'),
	Distric varchar(35) NOT NULL DEFAULT ('n/a'),
	Postal_Code varchar(10) NOT NULL DEFAULT ('n/a'),
	City varchar(40) NOT NULL DEFAULT ('n/a'),
	Transportation_Zone varchar(10) NOT NULL DEFAULT ('n/a'),
	Longitude varchar(10) NOT NULL DEFAULT ('n/a'),
	Latitude varchar(25) NOT NULL DEFAULT ('n/a'),
	Industry_Code varchar(10) NOT NULL DEFAULT ('n/a'),
	Contact_Person varchar(35) NOT NULL DEFAULT ('n/a'),
	Contact_Person_Number varchar(16) NOT NULL DEFAULT ('n/a'),
	Terms_of_Payment varchar(4) NOT NULL DEFAULT ('n/a'),
	Sales_Distric varchar(6) NOT NULL DEFAULT ('n/a'),
	Sales_Office varchar(4) NOT NULL DEFAULT ('n/a'),
	Customer_Group varchar(8) NOT NULL DEFAULT ('na'),
	Delivering_Plant varchar(4) NOT NULL DEFAULT ('n/a'),
	Incoterms varchar(3) NOT NULL DEFAULT ('n/a'),
	Customer_Group1 varchar(7) NOT NULL DEFAULT ('n/a_cg1'),
	Customer_Group2 varchar(7) NOT NULL DEFAULT ('n/a_cg2'),
	Customer_Group3 varchar(7) NOT NULL DEFAULT ('n/a_cg3'),
	Customer_Group4 varchar(7) NOT NULL DEFAULT ('n/a_cg4'),
	Sold_To varchar(10) NOT NULL DEFAULT ('n/a'),
	Ship_To varchar(10) NOT NULL DEFAULT ('n/a'),
	Payer varchar(10) NOT NULL DEFAULT ('n/a'),
	Bill_To varchar(10) NOT NULL DEFAULT ('n/a'),
	Salesman varchar(10) NOT NULL DEFAULT ('n/a'),
	Tax_Indicator varchar(1) NOT NULL,
	Credit_Limit bigint NOT NULL DEFAULT ((0)),
	Customer_Order_Block_all varchar(2),
	Customer_Order_Block varchar(2),
	Deletion_Flag_all varchar(1),
	Deletion_Flag varchar(1),
	NOO_Create_Date date,
	NOO_Approved_Date date,
	NOO_Update_Date date,
	Rt_Rw varchar(40),
	Desa_Kelurahan varchar(40),
	Kecamatan varchar(40),
	Kodya_Kabupaten varchar(40),
	Province_Code char(3),
	Create_Date date,
	Create_Time time,
	Flag smallint,
	Customer_Priority int,
	Tax_Class varchar(1),
	CONSTRAINT PK_Customer PRIMARY KEY (Customer_ID,Account_Group,Distribution_Channel,Division)
) ;