CREATE TABLE BOSNET1.dbo.TMS_PreRouteJob (
	RunId varchar(18) NOT NULL,
	Customer_ID varchar(40),
	DO_Number varchar(40) NOT NULL,
	Long varchar(100),
	Lat varchar(100),
	Customer_priority int,
	Service_time int,
	deliv_start varchar(5),
	deliv_end varchar(5),
	vehicle_type_list varchar(255),
	total_kg decimal(38,3),
	total_cubication decimal(38,3),
	DeliveryDeadline varchar(MAX),
	DayWinStart varchar(MAX),
	DayWinEnd varchar(MAX),
	UpdatevDate varchar(20),
	CreateDate varchar(20),
	isActive varchar(1) NOT NULL,
	Is_Exclude varchar(5),
	Is_Edit varchar(5),
	Product_Description varchar(40),
	Gross_Amount decimal(18,2),
	DOQty decimal(17,3),
	DOQtyUOM varchar(5),
	Name1 varchar(40),
	Street varchar(40),
	Distribution_Channel varchar(35),
	Customer_Order_Block_all varchar(2),
	Customer_Order_Block varchar(2),
	Request_Delivery_Date varchar(25),
	MarketId varchar(20),
	Desa_Kelurahan varchar(40),
	Kecamatan varchar(40),
	Kodya_Kabupaten varchar(40),
	Batch varchar(10),
	Ket_DO varchar(200)
) ;
