CREATE TABLE BOSNET1.dbo.TMS_ShipmentPlan (
	DO_Number varchar(40) NOT NULL,
	Customer_ID varchar(40),
	Total_KG decimal(17,3),
	Total_Amount decimal(18,2),
	Request_Delivery_Date date,
	Route varchar(10),
	Route_Description varchar(40),
	Item_Number varchar(40) NOT NULL,
	Plant varchar(4),
	Product_ID varchar(40),
	Product_Description varchar(40),
	Total_KG_Item decimal(17,3),
	Total_Cubication decimal(17,3),
	Gross_Amount decimal(18,2),
	Net_Amount decimal(18,2),
	Already_Shipment varchar(1),
	ItemCategory varchar(6),
	DOQty decimal(17,3),
	DOQtyUOM varchar(5),
	Batch varchar(10),
	HighLevelBatch varchar(40),
	Shift smallint,
	Expired_Date_Batch varchar(10),
	DOCreationDate date,
	DOCreationTime time,
	DOUpdatedDate date,
	DOUpdatedTime time,
	Create_Date date,
	Create_Time time,
	Flag smallint,
	NotUsed_Flag char(1),
	Order_Type varchar(4),
	Incoterm varchar(3),
	Good_Movement_Status varchar(1),
	CONSTRAINT PK_TMS_ShipmentPlan PRIMARY KEY (DO_Number,Item_Number)
) ;